name       : rtkit
version    : 0.13
release    : 2
source     :
    - https://github.com/heftig/rtkit/releases/download/v0.13/rtkit-0.13.tar.xz : a157144cd95cf6d25200e74b74a8f01e4fe51fd421bb63c1f00d471394b640ab
license    :
    - GPL-3.0-or-later
    - MIT # rtkit.c
component  : system.utils
homepage   : https://github.com/heftig/rtkit
summary    : Realtime Policy and Watchdog Daemon
description: |
    RealtimeKit is a D-Bus system service that changes the scheduling policy of user processes/threads to SCHED_RR (i.e. realtime scheduling mode) on request
builddeps  :
    - pkgconfig(libcap)
    - vim # Needs xxd which is part of this package
setup      : |
    patch -Np1 < $pkgfiles/0001-meson-actually-use-systemd_systemunitdir.patch
    %meson_configure -Dsystemd_systemunitdir=%libdir%/systemd/system/ \
                     -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -Dm00644 $pkgfiles/rtkit-daemon.service $installdir/%libdir%/systemd/system/rtkit-daemon.service
    # Cut down on the amount of journal log spam
    install -dm00755 $installdir/%libdir%/systemd/system/rtkit-daemon.service.d/
    echo -e "[Service]\nLogLevelMax=warning\n" > $installdir/%libdir%/systemd/system/rtkit-daemon.service.d/log.conf
    # set up system user
    install -Dm00644 $pkgfiles/rtkit.sysusers $installdir/%libdir%/sysusers.d/rtkit.conf
